-- AlterTable
ALTER TABLE "Buzz" ADD COLUMN     "shareOfHolders" INTEGER NOT NULL DEFAULT 40,
ADD COLUMN     "shareOfKols" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "shareOfOthers" INTEGER NOT NULL DEFAULT 10;
